'use strict';
const assert=require('node:assert/strict');
const {createAgentService,MENU_VERSION}=require('../agent-service.cjs');
let clock=Date.parse('2026-09-05T10:00:00Z');
const service=createAgentService({now:()=>clock,ttlMs:60000});
const menu=service.publicMenu('zh');
assert.equal(menu.items.length,13);
assert.equal(menu.menuVersion,MENU_VERSION);
const session=service.createSession({table:'1',language:'zh'},'http://127.0.0.1:8765');
assert.equal(session.status,'waiting_for_agent');assert.ok(session.agentUrl.includes(`session=${session.sessionId}`));
assert.ok(session._confirmationToken);assert.ok(!JSON.stringify(session).includes(session._confirmationToken),'confirmation secret must not be exposed in JSON');
const payload={requestId:'kotoha-demo-1',menuVersion:MENU_VERSION,table:'1',language:'zh',sessionId:session.sessionId,lines:[{itemId:3,quantity:1,optionKeys:['noLettuce']},{itemId:6,quantity:1,optionKeys:['large','sugar0','iceNone']}]};
const draft=service.createDraft(payload,'http://127.0.0.1:8765');
assert.equal(draft.status,'draft');assert.equal(draft.total,85);assert.equal(draft.sessionId,session.sessionId);assert.equal(draft.confirmationMode,'originating_session');assert.equal(draft.reviewUrl,undefined);
assert.equal(service.getSession(session.sessionId).status,'awaiting_confirmation');
assert.equal(service.createDraft(payload,'http://127.0.0.1:8765').draftId,draft.draftId,'request retry must be idempotent');
assert.throws(()=>service.createDraft({...payload,requestId:'bad-price',total:1}),/schema/);
assert.throws(()=>service.createDraft({...payload,requestId:'bad-option',sessionId:undefined,lines:[{itemId:3,quantity:1,optionKeys:['freeMeal']}]}),/unsupported option/);
assert.throws(()=>service.createDraft({...payload,requestId:'stale',menuVersion:'old'}),/stale/);
const wrongTableSession=service.createSession({table:'2',language:'zh'},'http://127.0.0.1:8765');
assert.throws(()=>service.createDraft({...payload,requestId:'wrong-table',sessionId:wrongTableSession.sessionId}),/table mismatch/);
assert.throws(()=>service.confirmSession(session.sessionId,'wrong'),/invalid session confirmation/);
const accepted=service.confirmSession(session.sessionId,session._confirmationToken);
assert.equal(accepted.status,'accepted');assert.equal(accepted.orderId,'C0001');
assert.equal(service.getSession(session.sessionId).status,'accepted');assert.equal(service.getSession(session.sessionId).orderId,'C0001');
assert.equal(service.confirmSession(session.sessionId,session._confirmationToken).orderId,'C0001','repeat confirmation must not duplicate');
assert.equal(service.listOrders().length,1);assert.equal(service.getOrder('C0001').total,85);
const expiring=service.createDraft({...payload,requestId:'expires',sessionId:undefined},'http://127.0.0.1:8765');clock+=61000;
assert.equal(expiring.confirmationMode,'review_url');assert.ok(expiring.reviewUrl.includes('/review?draft='));
assert.throws(()=>service.confirmDraft(expiring.draftId,new URL(expiring.reviewUrl).searchParams.get('token')),/expired/);
console.log('PASS: Agent airlock service tests');
