// Deterministic logic/static tests. Browser and mobile visual acceptance remain manual.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'main.js'),'utf8'),coreSource=fs.readFileSync(path.join(root,'ordering-core.js'),'utf8'),html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8');
let assertions=0;const check=(value,message)=>{assert.ok(value,message);assertions++};
function boot(storageBlocked=false){
  const nodes=new Map();const node=selector=>{if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',value:'',disabled:false,hidden:false,style:{},open:false,classList:{toggle(){},add(){},remove(){}},addEventListener(){},setAttribute(){},showModal(){this.open=true},close(){this.open=false}});return nodes.get(selector)};
  const context=vm.createContext({document:{querySelector:node,querySelectorAll:()=>[],documentElement:{},addEventListener(){}},localStorage:{getItem(){if(storageBlocked)throw Error('blocked');return null},setItem(){}},navigator:{languages:['en-US']},location:{search:'?table=1',href:'http://127.0.0.1:8765/?table=1'},URL,URLSearchParams,Math,scrollTo(){},setTimeout(){},clearTimeout(){}});
  vm.runInContext(coreSource+'\n'+source+'\n globalThis.api={state,menu,itemRules,optionPrices,addonRules,t,showView,openItem,toggleOption,addToCart,resetAi,submitOrder,restrictionAllows,startAiFlow,selectDirectItem,selectDirectOption,handleDirectText,agentUrl,renderAi};',context);return {...context.api,node};
}

const a=boot(true);check(a.state.lang==='en','Blocked localStorage must not prevent startup');a.state.lang='zh';a.showView('ai');
check(a.state.aiFlow==='entry','AI opens at shared ordering-method entry');
check(a.node('#ai-controls').innerHTML.includes('data-ai-entry="direct"')&&a.node('#ai-controls').innerHTML.includes('data-ai-entry="agent"'),'Entry offers exactly the direct and Agent paths');
a.startAiFlow('direct');check(a.state.directChoices.length===2&&a.state.directChoices.every(item=>[3,4,6,7].includes(item.id)),'Direct flow samples two merchant-configured dishes or drinks');
a.selectDirectItem(3);check(a.state.directStage==='option','Popping hamburger opens relevant options');a.selectDirectOption('noLettuce');a.selectDirectOption('cheese');
check(a.state.directStage==='addon'&&a.state.cart.length===1,'Finishing options adds one item and reaches add-on step');check(a.state.cart[0].optionKeys.includes('noLettuce')&&a.state.cart[0].unitPrice===70,'Direct options and authoritative price reach cart');
check(source.includes("state.view==='ai'||count===0"),'AI immersive scene always hides the legacy selected-items overlay');
a.selectDirectItem(11);check(a.state.directStage==='done'&&a.state.cart.length===2,'Popping snack adds it and reaches final review');check(a.node('#ai-results').innerHTML.includes('確認完成訂單'),'Final direct screen exposes explicit review control');a.showView('cart');a.submitOrder();check(a.state.view==='success','Valid direct demo order reaches success screen');

const drink=boot();drink.state.lang='zh';drink.showView('ai');drink.startAiFlow('direct');drink.selectDirectItem(6);check(drink.state.directGroups.map(group=>group.key).join(',')==='size,sweetness,ice','Drink bubbles progress through size, sweetness, and ice');drink.selectDirectOption('large');drink.selectDirectOption('sugar0');drink.selectDirectOption('iceNone');check(drink.state.cart[0].unitPrice===20&&drink.state.cart[0].optionKeys.includes('large'),'Drink option chain adds compatible option keys');
const typed=boot();typed.state.lang='zh';typed.showView('ai');typed.startAiFlow('direct');typed.state.directChoices=[typed.menu.find(item=>item.id===3),typed.menu.find(item=>item.id===4)];check(typed.handleDirectText('我想吃漢堡')&&typed.state.directItem.id===3,'Typed dish name enters the same bounded state machine');check(!typed.handleDirectText('請發明隱藏餐點'),'Unknown text cannot fabricate an order');

const agent=boot();agent.state.lang='zh';agent.showView('ai');agent.startAiFlow('agent');check(agent.node('#ai-results').innerHTML.includes('正在建立本次安全點餐入口'),'Agent path starts with a bounded session-creation state');agent.state.agentSession={sessionId:'S_test',status:'waiting_for_agent',agentUrl:'http://127.0.0.1:8765/agent?restaurant=clover-ai-ordering-demo&table=1&lang=zh&session=S_test'};agent.renderAi();check(agent.node('#ai-results').innerHTML.includes('id="agent-url"')&&agent.node('#ai-results').innerHTML.includes('session=S_test'),'Agent path exposes a session-bound URL');check(agent.agentUrl().includes('restaurant=clover-ai-ordering-demo')&&agent.agentUrl().includes('table=1'),'Agent URL preserves context');agent.state.agentSession={...agent.state.agentSession,status:'awaiting_confirmation',total:50,lines:[{name:'蘿蔔糕',quantity:1,lineTotal:35},{name:'紅茶',quantity:1,lineTotal:15}]};agent.renderAi();check(agent.node('#ai-results').innerHTML.includes('已收到訂單草稿')&&agent.node('#ai-results').innerHTML.includes('NT$50')&&agent.node('#ai-results').innerHTML.includes('data-action="confirm-agent-order"'),'Agent screen shows the session-bound human confirmation action');agent.state.agentSession={...agent.state.agentSession,status:'accepted',orderId:'C0001',orderStatus:'準備中'};agent.renderAi();check(agent.node('#ai-results').innerHTML.includes('訂單已確認')&&agent.node('#ai-results').innerHTML.includes('C0001'),'Agent screen exposes the accepted order state');

const normal=boot();normal.state.lang='zh';for(const id of [1,4,5]){normal.openItem(id);check(!normal.node('#dialog-options').innerHTML.includes('data-option-key="noOnion"'),`Item ${id} must not offer no-onion`)}normal.openItem(13);check(normal.node('#dialog-options').innerHTML.includes('data-option-key="ketchup"'),'Snack offers ketchup');check(normal.node('#dialog-options').innerHTML.includes('data-option-key="pepper"'),'Snack offers pepper');check(!normal.restrictionAllows(normal.menu[2],['cheese'],{kind:'allergy',filter:'dairy'}),'Allergy boundary rejects dairy add-on');

const htmlIds=new Set([...html.matchAll(/id="([^"]+)"/g)].map(match=>match[1]));const dynamicIds=new Set(['agent-url']);for(const match of source.matchAll(/\$\('#([^']+)'\)/g))check(htmlIds.has(match[1])||dynamicIds.has(match[1]),`Missing HTML id: ${match[1]}`);
const translationKeys=new Set([...html.matchAll(/data-i18n="([^"]+)"/g)].map(match=>match[1]));for(const lang of ['zh','ja','en','ko']){normal.state.lang=lang;for(const key of [...translationKeys,'aiEntryMessage','directOrder','agentOrder','directWelcome','addedDirect','confirmDirect','agentWelcome','copyAgentUrl'])check(normal.t(key)!==key,`Missing ${lang} translation: ${key}`);for(const item of normal.menu)check(Boolean(item[lang]&&item[lang+'Desc']),`Missing ${lang} menu data`)}
check(!source.includes('combo:'),'Unapproved combo price removed');check(!source.includes('Staff notified'),'No false staff notification');check(html.includes('class="home-icon"')&&html.includes('data-action="home" aria-label="回到首頁"'),'Top-left home control uses a house icon');check(html.includes('id="ai-chat-bar"')&&html.includes('id="ai-microphone"'),'AI scene retains text and microphone controls');check(!html.match(/id="ai-chat-input"[^>]*disabled/),'Text input is available for bounded direct-order names');check(css.includes('.ai-chat-bar { position:relative')&&!css.includes('.ai-chat-bar { position:fixed'),'Chat bar cannot cover controls');check(source.includes("state.aiFlow==='agent'")&&source.includes("chat.classList.toggle('hidden'"),'Agent screen hides restaurant conversation controls');check(source.includes("fetch('/api/speech'")&&source.includes('speechSynthesis')&&source.includes('SpeechRecognition'),'ElevenLabs speech has browser fallback and voice input remains feature-detected');check(source.includes("[3,4,6,7].includes(item.id)")&&source.includes("[11,12,13].includes(item.id)"),'Merchant pools are explicit');
check(source.includes("fetch('/api/agent-sessions'")&&source.includes('setTimeout(pollAgentSession,2000)'),'Agent screen creates and polls a server-issued session');
check(source.includes('}/confirm`')&&source.includes("credentials:'same-origin'"),'Agent confirmation stays in the originating browser session');
const core=boot();core.showView('ai');const markup=core.node('#ai-orb').innerHTML;check((markup.match(/class="core-dot-arrival"/g)||[]).length===96,'Core has 96 particles');check(!markup.includes('core-star'),'Core has no internal stars');check((markup.match(/class="core-wander"/g)||[]).length===6,'Six particles drift outward and return');check(css.includes('core-gather 2.8s')&&css.includes('core-return 11s'),'Core timing remains approved');check(css.includes('@keyframes core-breathe { 50% { transform:scale(1.08); } }'),'Core breathing remains approved');
console.log(`PASS: ${assertions} assertions (logic/static only; browser and mobile acceptance pending)`);
